### ISSUE TITLE
warning for a non existing variable

### ISSUE THREAD

**Issue by YonatanHanan** [JonAbrams/eslint-plugin-react-hooks-signals#1]
thanks for this plugin!
I have a small issue.

for this block of code
<img width="534" alt="image" src="https://github.com/JonAbrams/eslint-plugin-react-hooks-signals/assets/6177147/6ede3021-62f1-4415-aff2-fee444494a46">

The plugin wants me to add `option.value` to the dependencies, just to make it clear the `option.value` is not a signal.
<img width="822" alt="image" src="https://github.com/JonAbrams/eslint-plugin-react-hooks-signals/assets/6177147/34520e2b-3d39-4396-a700-22004fd27c1e">

**Comment by JonAbrams** [comment]
The eslitn plugin can't tell what truly is a signal or not, it just looks for `.value` being read on an object. So for false positives like this, add an eslint-disable-next-line. Not ideal, I know, but it's better than the alternative (missing signal deps).
